/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;


import static Ventanas.Menu.hashTable;
import java.io.File;
import proyecto2.Funciones;
import proyecto2.Lista;
import proyecto2.Nodo;
import proyecto2.Resumen;


/**
 *
 * @author alons
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public static BuscarAutor ba = new BuscarAutor ();
    
    public Buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        autor = new javax.swing.JButton();
        palabraclave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué tipo de busqueda deseas realizar?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 250, -1));

        autor.setBackground(new java.awt.Color(255, 153, 255));
        autor.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        autor.setText("Por autor");
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });
        jPanel1.add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, -1));

        palabraclave.setBackground(new java.awt.Color(255, 153, 255));
        palabraclave.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        palabraclave.setText("Por palabra clave");
        palabraclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraclaveActionPerformed(evt);
            }
        });
        jPanel1.add(palabraclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        
        Nodo<Resumen> resumenes = (Nodo<Resumen>)Funciones.getResumenes(hashTable).getFirst();
        String autoress = "";
        ba.autores.removeAllItems();
        while(resumenes!=null){
            String[] autoresa = resumenes.getData().getAutores().split("\n");
            for (int i = 0; i<autoresa.length;i++){
                autoresa[i] = autoresa[i].trim();
                if(!autoress.contains(autoresa[i])){
                    ba.autores.addItem(autoresa[i]);
                    autoress+=autoresa[i]+",";
                }
            }
            resumenes = resumenes.getpNext();
        }
        ba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_autorActionPerformed

    private void palabraclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraclaveActionPerformed

        // TODO add your handling code here:
        Menu.busqueda_palabras.setVisible(true);
        dispose();
        this.dispose();

    }//GEN-LAST:event_palabraclaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton palabraclave;
    // End of variables declaration//GEN-END:variables
}
