/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyecto2.Funciones;
import proyecto2.Lista;
import proyecto2.Resumen;

/**
 *
 * @author alons
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null); // centrar pantalla
    }
    public static Menu menu = new Menu();
    public static Lista[] hashTable = Funciones.newHashTable(13);
    public static Lista[] hashTable2 = Funciones.newHashTable(29);
    public static Lista resumenes;
    public static String titulos;
    public static BusquedaPalabras busqueda_palabras = new BusquedaPalabras();
    public static Boolean cargado = false;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        analizar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(255, 153, 255));
        salir.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        salir.setText("Salir del sistema");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, -1));

        agregar.setBackground(new java.awt.Color(255, 153, 255));
        agregar.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        agregar.setText("Agregar resumen");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, -1));

        analizar.setBackground(new java.awt.Color(255, 153, 255));
        analizar.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        analizar.setText("Analizar resumen");
        analizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });
        jPanel1.add(analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, -1));

        buscar.setBackground(new java.awt.Color(255, 153, 255));
        buscar.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        buscar.setText("Buscar resumen");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 130, -1));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 140));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 540, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        Funciones.GuardarTxt(hashTable);
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        File file = Funciones.FileChooser();
        if (file!=null){
            Resumen resumen = Funciones.LeerTxt(file);
            if (resumen.getCuerpo() != null && resumen.getTitulo() != null && resumen.getAutores() != null && resumen.getPalabras_claves() != null){
                Funciones.Insert(resumen, hashTable, hashTable2);}
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
        // TODO add your handling code here:

        
        if (Funciones.esVacio(hashTable)) {
           JOptionPane.showMessageDialog(null, "Debe cargar al menos un (1) resumen para acceder a esta función");
        }else {
            resumenes = Funciones.getResumenes(hashTable);
            resumenes.OrdenarCrec();
            titulos = resumenes.getTitulos();
            AnalizarResumen analizar_resumen = new AnalizarResumen();
            Funciones.AsignarTitulos(titulos, analizar_resumen.lista);
            analizar_resumen.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_analizarActionPerformed
                                    

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        resumenes = Funciones.getResumenes(hashTable);
        if(!resumenes.isEmpty()){
            Buscar b = new Buscar();
            b.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "No hay resumenes cargados");
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                menu.setVisible(true);
                Imagen im = new Imagen(Header); 
                Header.add(im).repaint(); //Carga el logo
                
                Path currentRelativePath = Paths.get("resumenTODO.txt");
                String s = currentRelativePath.toAbsolutePath().toString();
                File archivo = new File (s);
                
                if (!cargado && archivo.exists()) {
                    int carga = JOptionPane.showConfirmDialog(null, "¿Desea restaurar la sesión previa?","Precarga de datos", 0, 1);
                    if (carga==JOptionPane.YES_OPTION) {
                        
                        
                        Funciones.Precarga(hashTable, hashTable2);
                    }
                    cargado = true;
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel Header;
    private javax.swing.JButton agregar;
    private javax.swing.JButton analizar;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
